### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by SharpNoiZy** [cdjackson/HABmin2#107]
Hi,

just want to ask if the project is dead or if there is specific reason for nearly no commits (6 since June)
I hope that everything is fine because this UI look so damn good! :)

Kind regards

**Comment by cdjackson** [comment]
Ummm, it's not dead and there have been a lot of commits since June - just nothing merged to master since June. Once the oh2 Zwave binding is released I'll merge the dev branch to master.

**Comment by cdjackson** [comment]
Just to clarify, there have been around 90 commits since the end of June :)

**Comment by SharpNoiZy** [comment]
Great to hear!
What do you think, will OpenHab2 Beta with your Zwave Binding released this year?
Maybe as a Christmas gift? :)

**Comment by cdjackson** [comment]
Hopefully. I'm just about to send it out to a few ripple to test. Currently there are two testers so hopefully we'll start to roll it out in a week or three. The database might take a bit to convert though....

**Comment by greenimz** [comment]
Hi, 

I was just wondering how testing was going and how far you might be from a release?
I'm happy to help use test.

Thanks for all your effort on a great UI :)

**Comment by cdjackson** [comment]
Still ongoing - there are a few more people testing now, but we’re working on getting the database sorted out so that we can better control OH1 and OH2 databases otherwise it will be a nightmare to manage…

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide>

**Comment by greenimz** [comment]
Great, thanks for the update.
