### ISSUE TITLE
Can any binding render actionbuttons in habmin

### ISSUE THREAD

**Issue by marcelrv** [cdjackson/HABmin2#119]
Hi Chris,
For my bindings I want to use some action buttons in habmin like you have with the zwave binding.
I understood that you use specific groups for this purpose. Can the same be used in any binding?
Are there specific groupnames to be used?
Any requirements to the button definition?

**Comment by cdjackson** [comment]
Hi Marcel,
What I’m currently doing in the latest HABmin2 is to use a parameter group called ‘actions’. This group gets rendered in a dropdown button list called ‘Tools’…  It should be no problem for you to do the same - I’ve mentioned to Kai that we ought to standardise these names so everyone knows what to expect, and the UIs render consistently, but it’s not done yet…

I chose a dropdown menu in the end as buttons on a toolbar take too much space and will cause problems if you have more than a few of them - a menu style is more adaptable…

Cheers
Chris

**Comment by marcelrv** [comment]
Cool. Indeed was able to see this happening now.
Still struggling with 2 things: 

1) in the zwave binding, I see you do a 
```
     <parameter name="controller_hardreset" type="text" groupName="actions">
                <label>Hard Reset Controller</label>
                <description>Hard resets the Z-Wave stick - this will erase all configuration from the controller!.</description>
                <advanced>true</advanced>
            </parameter>
```
with type text, but seems like you are sending an integer when the button is pressed. When using it in my binding I get a  type conversion error. I'll change the type to a number for now.

13:53:50.952 [DEBUG] [nternal.handler.MaxCubeBridgeHandler] - Initializing MAX! Cube bridge handler.                                                            13:53:50.966 [WARN ] [.smarthome.config.core.Configuration] - Could not set field value for field 'cubeReboot': Can not set java.lang.String field org.openhab.binding.max.config.MaxCubeBridgeConfiguration.cubeReboot to java.math.BigDecimal                                                                                 java.lang.IllegalArgumentException: Can not set java.lang.String field org.openhab.binding.max.config.MaxCubeBridgeConfiguration.cubeReboot to java.math.BigDecimal                           

2) How to prevent that the action is now executed each time an config update is done, as in the configuration it is now stored as a 0 value (after the first click), and this value will remain 0 all of the time. I did not see this value increasing or changing when clicking it again?
In the zwave binding I did not see you changing the value back to anything else.

**Comment by cdjackson** [comment]
> with type text, but seems like you are sending an integer when the button is pressed. When using it in my binding I get a type conversion error. I'll change the type to a number for now.
> 
Yes - good point. With the actions, at the moment I just send bank data, but you’re right, what is done here isn’t correct. For most of the configuration, I pass the response through a function to ensure type is correct, but I’ve not done it here. I’ll change this in HABmin… In the longer term, I see the ability to have actions with options, so this needs to be resolved.

> 2) How to prevent that the action is now executed each time an config update is done, as in the configuration it is now stored as a 0 value (after the first click), and this value will remain 0 all of the time. I did not see this value increasing or changing when clicking it again?
> In the zwave binding I did not see you changing the value back to anything else.
> 
Ummm… How are you doing your config updates in the binding? The only time I update the configuration is when I receive the configuration updated call, so to me at least, it doesn’t matter. This is exactly the use case for which this method was introduced since before this I think the configuration was updated through the reinitialisation of the thing, and then you can’t detect if someone has asked for an update, or if it’s static data.  If you wanted to detect change for some reason (i.e. to do initialisation other than when the config update method is called, then you’d need to change the value).

You’re obviously looking at some of the code I’ve been playing with in the last day or so - are you also running a new HABmin (i.e. compiling it yourself)? If not, I’ll send you an update it you want?

**Comment by cdjackson** [comment]
I should have added - I think if you change config through the PaperUI, then it will reinitialise the thing rather than call the config update method...

**Comment by marcelrv** [comment]
I'm using one that you build a month or 2 ago. If you have a newer one I can use for testing would be great.

Yes, indeed I see different behaviour on paperui. I now worked send it by directly changing the value back to something else.

Do you plan to remove the action group from the regular properties section?

**Comment by cdjackson** [comment]
> 
> Do you plan to remove the action group from the regular properties section?
> 
> 

Yes - this is done…

Updated version here -: https://github.com/cdjackson/HABmin2/raw/theme/output/org.openhab.ui.habmin_2.0.0.SNAPSHOT-0.0.15.jar

**Comment by marcelrv** [comment]
Thanks Chris.
Indeed with your latest build it's gone. 

FYI:
Have PR with this functionality included 
https://github.com/openhab/openhab2-addons/pull/650
