### ISSUE TITLE
HABmin2 Binding not visable

### ISSUE THREAD

**Issue by globus243** [cdjackson/HABmin2#138]
I'm running the latest openHAB and installed HABmin2 using your tutorial https://github.com/cdjackson/HABmin2/wiki/OpenHAB-1-installation

however, I can't see the bindings and some other parts [for example, this is my Bindings section](http://imgur.com/h4nUFz4) but depending on the zwave binding (the jar file) I choose i get either this or the spinner which keeps rotating  [and this is what my Sidemap Section looks like](http://imgur.com/hqFHP8A) 

I don't get any useful log entry.
I have absolutely no clue whats going wrong here, any suggestion is appreciated.

**Comment by cdjackson** [comment]
It is no longer possible to run HABmin2 under openHAB1.

**Comment by globus243** [comment]
Ok, thank you, updated OH now it works.

before I file another issue, may I ask where the zwave inclusion and exclusion options are? I cant find them anywhere.

**Comment by cdjackson** [comment]
Just start a discovery - this will put the controller into inclusion. For exclusion, it’s in the tools menu - select the controller (in thing config), then go to the tools menu and select advanced setting. Then look in the tools menu again.

**Comment by mikef2501** [comment]
Hi there - I have a tangentially-related question:
I'm currently running OH1 with HM2 (both versions were downloaded about 8 weeks ago from their respective websites), and I'd like to update both to the latest builds.  Is there was a recommended way to update OpenHab from 1 to 2?  Also, updating HabMin just involves downloading the latest JAR from the downloads webpage, right?

Thanks a bunch!
--Mike

**Comment by cdjackson** [comment]
It's a shallow tangent :)

Firstly, HABmin2 is really now being directed more toward OH2 rather than OH1, so I probably wouldn't recommend using a new version of HABmin2 with OH1 - you'll possibly find less will work compared to the version you have now.

For the upgrade, you're probably best to ask questions on the openhab forum. However, you _should_ be able to take your items and bindings and use them without too much hassle in OH2 in an OH1 sort of way.

Yes, for upgrading HABmin-2, you can just drop the new JAR in the addons folder. For HABmin-1, it's a bit more complex as you also need to update the webapps folder.

**Comment by mikef2501** [comment]
Thanks, Chris.  As for the OpenHAB2 forum, it's not on GitHub, like HM2, right?  I see one labeled OpenHAB on GitHub, but is the best place to go this website:  

https://community.openhab.org/c/openhab-2

Thanks for the patience - just getting started   :)

**Comment by cdjackson** [comment]
Yep - that link is the best place (it's what I meant by the openhab forum, but I should have been more specific) :)

Cheers
Chris

**Comment by mikef2501** [comment]
No problem.  Thanks!
