### ISSUE TITLE
Dutch language

### ISSUE THREAD

**Issue by ViperRNMC** [cdjackson/HABmin2#172]
Hi, don't know how to upload it, but here are the Dutch translation files.

[nl-NL.zip](https://github.com/cdjackson/HABmin2/files/284248/nl-NL.zip)

**Comment by cdjackson** [comment]
That’s great - thanks - I’ll add them over the next day or two.

Cheers
Chris

**Comment by cdjackson** [comment]
This should now be added in the latest snapshot

**Comment by ViperRNMC** [comment]
Thanks, works nice, i see some english text with the dutch translation on, i think not every item is listed

**Comment by cdjackson** [comment]
You’re right, there may be some hard coded strings. Please feel free to list this, or provide a picture or something so I can change them.

Note also that I added this to the online editor

http://www.cd-jackson.com/index.php/openhab/habmin-translator <http://www.cd-jackson.com/index.php/openhab/habmin-translator>

**Comment by cdjackson** [comment]
I will close this since it's now included. What I would suggest is that if you find any strings that are in English and you can't find a translation, then please open an issue and I'll try and solve this. There might be a couple that are hard to add to the translation, but I'd like most, or preferably all strings to be translated.

Thanks again for doing this - I know there are quite a few Dutch people using OH and HABmin, so I'm sure it's appreciated by many people :)
