### ISSUE TITLE
Empty Habmin 2

### ISSUE THREAD

**Issue by trusk89** [cdjackson/HABmin2#23]
Hello,

Since updating to the latest 0.9 version of Habmin 2 I just get a black page at login, like so http://imgur.com/p6PjJ7d. Anyone knows how to fix it? I've temporarily downgraded to 0.8 and it worked fine, so the problem is just in 0.9

Tried both safari and chrome.

**Comment by SteFiD93** [comment]
Hello,

I too have the same problem, are the new Empowerment Website Project and thought it was just my problem, I have not tried the 0.8, but I know that if I download the debug version works well, I mean the zip habmindebug

**Comment by trusk89** [comment]
You're right. Debug works. Thanks!

**Comment by SteFiD93** [comment]
nothing, in any case we hope will give us solutions to the problem.

**Comment by JuhnuFin** [comment]
Same issue here (OpenHAB 1.7.0 snapshot). HABmin 1 is installed and works. 

Firefox/Chrome DevTools throw these errors on /habmin2 or /habmin2/index.html:

URIError: malformed URI sequence HABmin2-0.0.9.js:68:20726
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. index.html
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] <unknown>
Error: [$injector:modulerr] Failed to instantiate module HABmin due to:
[$injector:modulerr] Failed to instantiate module templates-app due to:
[$injector:nomod] Module 'templates-app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=templates-app
d/<@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:10:20442
kb/</</<@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:10:28774
b@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:10:28346
kb/</<@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:10:28658
n/<@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:11:5089
f@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:10:20825
n@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:11:4937
n/<@http://192.168.1.1:8080/habmin2/assets/HABmin2-0.0.9.js:11:5106
f@http://192.168.1.1:8080/hab HABmin2-0.0.9.js:10:20441

**Comment by cdjackson** [comment]
This normally happena when theres a problem loading a file - maybe ive not included a new file into the repo...

In chrome can you open devleoppers tools and see what the error is when you load thw software?


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Alex Bartiș <notifications@github.com> </div><div>Date:30/03/2015  08:29  (GMT+00:00) </div><div>To: cdjackson/HABmin2 <HABmin2@noreply.github.com> </div><div>Subject: [HABmin2] Empty Habmin 2 (#23) </div><div>
</div>Hello,

Since updating to the latest 0.9 version of Habmin 2 I just get a black page at login, like so http://imgur.com/p6PjJ7d. Anyone knows how to fix it? I've temporarily downgraded to 0.8 and it worked fine, so the problem is just in 0.9

Tried both safari and chrome.

**Comment by cdjackson** [comment]
Ah - thanks. I know what this error is. It’s caused by the French translation - I fixed it yesterday. I’ll try and release an update tonight or tomorrow.

**Comment by trusk89** [comment]
Yep, some words on the debug version appear in french.

-- --

*"Nu lasa nimic intre tine si visele tale."*
--
<http://www.blog.alexbartis.com>

*Alex Bartis, *
iOS Developer @ Fortech

www.alexbartis.com | facebook.com/bartis.alex | twitter.com/alexbartis

**Comment by trusk89** [comment]
And going to COnfiguration > Items opens the Rule page.

-- --

*"Nu lasa nimic intre tine si visele tale."*
--
<http://www.blog.alexbartis.com>

*Alex Bartis, *
iOS Developer @ Fortech

www.alexbartis.com | facebook.com/bartis.alex | twitter.com/alexbartis

**Comment by cdjackson** [comment]
> On 30 Mar 2015, at 21:14, Alex Bartiș <notifications@github.com> wrote:
> 
> And going to COnfiguration > Items opens the Rule page.

This isn’t supported at the moment.

**Comment by cdjackson** [comment]
I've updated the snapshot builds - hopefully this fixes the problem?

**Comment by trusk89** [comment]
Yep, it's fixed, thank you Chris!

-- --

*"Nu lasa nimic intre tine si visele tale."*
--
<http://www.blog.alexbartis.com>

*Alex Bartis, *
iOS Developer @ Fortech

www.alexbartis.com | facebook.com/bartis.alex | twitter.com/alexbartis

**Comment by cdjackson** [comment]
Thanks.
