### ISSUE TITLE
Doesnot show up the installed bindings

### ISSUE THREAD

**Issue by nirozjung** [cdjackson/HABmin2#57]

**Comment by cdjackson** [comment]
Please provide some sort of description about your problem - otherwise I’m afraid it’s difficult for me to guess what’s wrong.

**Comment by nirozjung** [comment]
I have zwave binding 1.5.0-SNAPSHOT.jar, 1.7.0-SNAPSHOT.jar and io.habmin-1.5.0-SNAPSHOT.jar and  io.habmin-1.5.0-SNAPSHOT.jar both in addons. Also, i have both habmin and habmin2 in webapps folder. I am using openhab 1.6.2.  I have sitemap and items loaded in habmin but all the rest doesnot. After clicking in charts,it is only loading but nothing appears. I cannot add or edit dashboards. Also, it doesnot show my rules. I have my persistence with mysql.  Am i doing right.

**Comment by cdjackson** [comment]
> I have zwave binding 1.5.0-SNAPSHOT.jar, 1.7.0-SNAPSHOT.jar and io.habmin-1.5.0-SNAPSHOT.jar and io.habmin-1.5.0-SNAPSHOT.jar both in addons.
> 
Firstly, I would recommend using the latest versions since things like the dashboard are VERY new. Version 1.5 is now very old.


> Also, i have both habmin and habmin2 in webapps folder. I am using openhab 1.6.2.
> 
Again - you have a mixture of versions...


> I have sitemap and items loaded in habmin but all the rest doesnot. After clicking in charts,it is only loading but nothing appears.
> 
This should work fine - I’m not sure though why you would have problems. Have you saved any charts - you need to select items, and then save the chart...


> I cannot add or edit dashboards.
> 
Dashboards are very new and not supported in 1.5


> Also, it doesnot show my rules.
> 
The rule editor doesn’t show normal rules - it allows editing of rules with the block editor, but not rules that you write yourself.

**Comment by nirozjung** [comment]
Hi, now I tried with only binding.zwave.1.7.0-SNAPSHOT.jar and  io.habmin-1.7.0-SNAPSHOT.jar in addons folder. My openhab as I said is 1.6.2. And, I have only habmin2 in webapps folder. I still have the same problem. Neither the rules loads, neither could I edit the items for charts.  You mean, dashboard functions is only in Openhab 2?? I am confused.

**Comment by cdjackson** [comment]
> Neither the rules loads,

What rules won't load? The rule editor is a graphical block editor - have you designed these rules yet?
https://github.com/cdjackson/HABmin2/wiki/Graphical-Rule-Designer

> neither could I edit the items for charts. 

Do you get a list of items? In the chart view, click on the button in the top left corner and change it to ITEMS instead of CHARTS. Then you can create and save charts. If you haven't done this, and actually saved some charts, then you can't load them? 
https://github.com/cdjackson/HABmin2/wiki/Charting
Or have you created some charts, and now they don't load? It's hard to say what isn't loading from your email.

> You mean, dashboard functions is only in Openhab 2??

No - I mean that you need to use the latest HABmin JAR which should support the dashboards for saving charts (that have already been designed as I said above) and gauge widgets.
https://github.com/cdjackson/HABmin2/wiki/Dashboard-Overview

**Comment by nirozjung** [comment]
Thanx for the swift response , Yes, now with  binding.zwave.1.6.2.jar , io.habmin-1.7.0-SNAPSHOT.jar and io.habmin.ui.habmin_2.0.0.SNAPSHOT-0.0.14.jar (not active only installed), I get list of items loaded on the left after clicking dropdown in charts. I can select the items and in settings select the respective persistence service, but the Edit Chart and Delete Chart is not clickable. There is no any save buttons. I have not created any charts and rules in habmin. I just expect it to display my existing rules, sitemap is displayed.

**Comment by cdjackson** [comment]
> I get list of items loaded on the left after clicking dropdown in charts. I can select the items and in settings select the respective persistence service,
Can you then click the “Play” button i.e., the one that looks like > and then get a chart? Once you select the items, then click SAVE to save the chart in the TOOL menu (the button that looks like a cog!!
Have a look at the wiki -:
https://github.com/cdjackson/HABmin2/wiki/Charting <https://github.com/cdjackson/HABmin2/wiki/Charting>


> but the Edit Chart and Delete Chart is not clickable.
Until you have saved a chart, you can’t delete it or save it!


> There is no any save buttons.
It is in the tool menu. Have a look at the second image i the following wiki-:
https://github.com/cdjackson/HABmin2/wiki/Charting <https://github.com/cdjackson/HABmin2/wiki/Charting>


> I have not created any charts and rules in habmin. I just expect it to display my existing rules, sitemap is displayed.
Currently HABmin is designed to use the block editor.

**Comment by cdjackson** [comment]
> It is in the tool menu. Have a look at the second image i the following wiki-:

Sorry - that should be the first image - not second.

**Comment by nirozjung** [comment]
I donot see any play button, only setting button is visible (even after selecting the item).

**Comment by cdjackson** [comment]
Ok - this is an old bug but I need to release a new version. I’ll do that later tonight...

**Comment by cdjackson** [comment]
Any progress?

**Comment by nirozjung** [comment]
Just tested in my local machine. Everything looks fine with charts, can be saved and visualized in dashboard but still the installed bindings are not visible. 
Thanks Chris for your help.

**Comment by cdjackson** [comment]
> On 21 Jun 2015, at 15:21, nirozjung <notifications@github.com> wrote:
> 
> but still the installed bindings are not visible. 

Unfortunately, other than for zwave, the binding information is only available in OpenHAB2.
